# Generated by Django 4.1.3 on 2022-11-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0002_remove_definition_definition_remove_definition_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.IntegerField(choices=[(1, 'Subscriber'), (2, 'Lead'), (3, 'MQL'), (4, 'SQL'), (5, 'Opportunity'), (6, 'Costumer')]),
        ),
    ]
