# Generated by Django 4.1.3 on 2022-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0003_alter_stage_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.CharField(choices=[(1, 'Subscriber'), (2, 'Lead'), (3, 'MQL'), (4, 'SQL'), (5, 'Opportunity'), (6, 'Costumer')], max_length=45),
        ),
    ]
