# Generated by Django 4.1.3 on 2022-11-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0004_alter_stage_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.CharField(max_length=75),
        ),
    ]
