# Generated by Django 4.1.3 on 2022-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0005_alter_stage_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='owner_team',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Marketing'), (2, 'Sales'), (3, 'Customer Care')], default= 1),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_tools',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_trigger',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Subscriber'), (2, 'Lead'), (3, 'Mql'), (4, 'Sql'), (5, 'Opportunity'), (6, 'Customer')], default=''),
        ),
    ]
