# Generated by Django 4.1.3 on 2022-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0006_stage_owner_team_stage_stage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='owner_team',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Marketing'), (2, 'Sales'), (3, 'Customer Care')], default=0),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Subscriber'), (2, 'Lead'), (3, 'Mql'), (4, 'Sql'), (5, 'Opportunity'), (6, 'Customer')], default=0),
        ),
    ]
