# Generated by Django 4.1.3 on 2022-11-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0008_alter_stage_owner_team_alter_stage_stage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='owner_team',
        ),
    ]
