# Generated by Django 4.1.3 on 2022-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcs', '0010_stage_owner_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='owner_team',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Marketing'), (2, 'Sales'), (3, 'Customer Care')], default=1),
        ),
    ]
